# Generated by Django 2.2 on 2021-06-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0002_group_prayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users_in_this_group',
            field=models.ManyToManyField(related_name='users_groups', to='solo_app.User'),
        ),
    ]
