# Generated by Django 2.2 on 2021-06-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0004_comment_wall_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall_message',
            name='user_likes',
        ),
        migrations.AddField(
            model_name='wall_message',
            name='group_id',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='solo_app.Group'),
            preserve_default=False,
        ),
    ]
