# Generated by Django 2.2 on 2021-06-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0005_auto_20210617_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
